# Generated by Django 3.0.2 on 2020-02-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0005_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_id', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=255)),
                ('Quantity', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
