# Generated by Django 3.0.2 on 2020-02-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0006_auto_20200213_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Quantity',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
