# Generated by Django 3.0.2 on 2020-02-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0007_auto_20200213_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mywebsiteapp.User'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='P_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mywebsiteapp.Product'),
        ),
    ]
