# Generated by Django 2.2.3 on 2020-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0010_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Product',
        ),
        migrations.AddField(
            model_name='cart',
            name='Product',
            field=models.ManyToManyField(blank=True, null=True, to='Mywebsiteapp.Product'),
        ),
    ]
