# Generated by Django 2.2.3 on 2020-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0012_auto_20200216_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Product',
        ),
        migrations.AddField(
            model_name='cart',
            name='Product',
            field=models.ManyToManyField(blank=True, null=True, to='Mywebsiteapp.Product'),
        ),
    ]
