# Generated by Django 3.0.2 on 2020-02-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0014_auto_20200216_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Quantity',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
