# Generated by Django 2.2.3 on 2020-09-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0017_auto_20200218_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
