# Generated by Django 2.2.3 on 2020-10-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0020_auto_20201022_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mywebsiteapp.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
