# Generated by Django 2.2.3 on 2020-10-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsiteapp', '0021_auto_20201023_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0, null=True)),
                ('Email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mywebsiteapp.User')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mywebsiteapp.Product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
